app/models.py
#from typing_extensions import Required
from werkzeug.security import check_password_hash, generate_password_hash
from . import db
from flask_login import UserMixin
from . import login_manager
from flask import Flask
class Movie:
    """
    Movie class to define movie objects
    """

    def __init__(self, id, title, overview, poster, vote_average, vote_count):
        self.id = id
        self.title = title
        self.overview = overview
        self.poster = 'https://image.tmdb.org/t/p/w500/' + poster
        self.vote_average = vote_average
        self.vote_count = vote_count

#database models

#retrieving a user
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(db.Model, UserMixin):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_hash = db.Column(db.String(255))

    pass_secure  = db.Column(db.String(255))


    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f"User {self.username}"

class Role(db.Model):
    __tablename__ = "roles"

    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy="dynamic")

    def __repr__(self):
        return f"User {self.name}"




class PhotoProfile(db.Model):
    __tablename__ = 'profile_photos'

    id = db.Column(db.Integer,primary_key = True)
    pic_path = db.Column(db.String())
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required

class ReviewForm(FlaskForm):

    title = StringField('Review title',validators=[Required()])
    review = TextAreaField('Movie review', validators=[Required()])
    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from .config import DevConfig
from werkzeug.utils import secure_filename
from werkzeug.datastructures import  FileStorage
from flask_bootstrap import Bootstrap
from .config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.sessin_protection = "strong"
login_manager.login_view = "auth.login"
photos = UploadSet('photos',IMAGES)
mail = Mail()

def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    mail.init_app(app)
    login_manager.init_app(app)
    # Registering the blueprint
    from .main import main as main_blueprint
    from flask_uploads import UploadSet,configure_uploads,IMAGES
    app.register_blueprint(main_blueprint)
    #authentication
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')
    # setting config
    from .requests import configure_request
    from flask_uploads import configure_uploads
    configure_request(app)
    # configure UploadSet
    configure_uploads(app,photos)
    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error

app/main/views.py
from os import popen
from flask import render_template,request,redirect,url_for,abort
from . import main
from ..requests import getMovies, get_movie,search_movie
from flask_login import login_required
from .. import db,photos

from ..models import User,PhotoProfile
from ..forms import ReviewForm,UpdateProfile
from app import review
from ..forms import ReviewForm
Review = review.Review

#app
@main.route("/")
def index():
    """
    view root page that returns the index page and its data
    """
    message = ""
    #movies
    popular_movies = getMovies("popular")
    upcoming_movie = getMovies("upcoming")
    get_showing_movies = getMovies("now_playing")
    title = "home - Welcome to the best movie review website online"
    search_movie = request.args.get("movie_query")
    if search_movie:
        return redirect(url_for("main.search", movie_name = search_movie))
    else:
        return render_template("index.html", message = message, title = title, popular = popular_movies, upcoming = upcoming_movie, showing = get_showing_movies)

#profile
@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)
#movie details
@main.route("/movie/<int:id>")
def movie(id):
    """
    view function that returns movie id and its data
    """
    movie = get_movie(id)
    title = f"{movie.title}"
    review = Review.get_reviews(movie.id)
    return render_template("movie.html", title = title, movie = movie, review = review)


#search movie function
@main.route("/search/<movie_name>")
def search(movie_name):
    """
    View function to display the search results
    """
    movie_name_list = movie_name.split(" ")
    movie_name_format = "+".join(movie_name_list)
    searched_movies = search_movie(movie_name_format)
    title = f" search results for {movie_name}"
    return render_template("search.html", movies=searched_movies)



@main.route('/movie/review/new/<int:id>', methods = ['GET','POST'])
def new_review(id):
    form = ReviewForm()
    movie = get_movie(id)

    if form.validate_on_submit():
        title = form.title.data
        review = form.review.data
        new_review = Review(movie.id,title,movie.poster,review)
    
        new_review.save_review()
       
        return redirect(url_for('main.movie',id = movie.id))

    title = f'{movie.title} review'
    return render_template('new_review.html',title = title, review_form=form, movie=movie)



@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)


#photos logic
@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
<!DOCTYPE html>
{% extends 'bootstrap/base.html'%}

<!--navbar block-->
{% block navbar %} 
{% include "navbar.html" %}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import 'macros.html' as macro%}
<!-- Styles block -->

{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
  
{% endblock %}
<!--content block-->
{% block content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
<style>
    body {
        background-image: url(../static/images/background.jpg);
        background-repeat: no-repeat;
        background-size: cover;
        min-width: 100%;
        min-height: 100%;
    }
</style>
<body>
        <h1>{{ message }}</h1>
        <!--search movies-->
        <div class="container">
            <div class="text-center">
            <form class="form-inline">
                <div class="form-group mb-2">

                  <input type="text" name="movie_query" placeholder="Search for a Movie" class="form-control">
                </div>
                <div class="form-group mx-sm-3 mb-2">
                 </div>
                 <input type="submit"  class="btn btn-primary" value="search" class="btn btn-default">
              </form>
              </div>
        </div>
        <!--Popular movie section-->
        <h3 style="margin: 5rem; text-align: center; color: white; display: inline;">Popular movies</h3>
        <ul>
            {{ macro.displayMovieList(popular)}}
        </ul>

        <!--upcoming movies-->
        <h3 style="margin: 5rem; margin-bottom: 3rem; text-align: center; color: white;">Upcoming movies</h3>
        <ul>
            {{ macro.displayMovieList(upcoming)}}
        </ul>
        <!--Now showing movie-->
        <h3 style="margin: 5rem; margin-top: 5rem; text-align: center; color: white;">Movies showing now</h3>
        <ul>
            
            {{ macro.displayMovieList(now_showing)}}
        </ul> 
        </div>
        {% endblock %}
    </body>
</html>

app/templates/macros.html
{% macro displayMovieList(movie_list) %}
{% for movie in movie_list %}
<div class="col-xs-12 col-sm-4 col-md-2 col-lg-2 movie-card">
    <img src="{{ movie.poster }}" alt="{{ movie.title }} poster" class="img-responsive">
    <li class="text-center">
        <a href="/movie/{{movie.id}}">
            {{ movie.title|truncate(10)}}</a>
            
    </li>

</div>

{% endfor %}

<!-- Displaying reviews macro -->
{% macro displayReviews(review_list) %}
    {% for review in review_list %}
    <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 review-card">
        <h2> {{ review.title}} </h2>
        <p> {{ review.review | truncate(30) }}</p>
    </div>
    {% endfor %}
{% endmacro %}
{% endmacro %}

app/templates/movie.html
{% extends "base.html" %}
{% block title %}
{% endblock %}
{% block content %}
{% import 'macros.html' as macro%}
<div class="container">
    <!--poster background-->
    <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 posterPath" style="background: url({{movie.poster}}) no-repeat center center">

    </div>
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 movie-details">
        <h3>{{movie.poster_path}}</h3>
        <h3>{{ movie.title }}</h3>

        <p class="overview"> {{ movie.overview }}</p>
        <p class="ratings"> <b> {{ movie.vote_average }}</b> - <i>{{ movie.vote_count}} votes </i> </p>


    </div>
</div>






<div class="row">

    <h1>Reviews</h1>
    <hr>

    {% if reviews %}
        {{macro.displayReviews(reviews)}}

    {% else%}
        <h3 class="text-center">This movie has no reviews </h3>

        <a class="btn btn-success btn-lg text-center" href="/movie/review/new/{{movie.id}}"> Write a new review</a>
    {% endif %}

</div>
{% endblock %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a style="margin-left: 1rem;" class="navbar-brand" href="/"> Watchlist </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
    </ul>
    
<ul class="nav navbar-nav navbar-right" style=" margin-left: 10rem; ">
    {% if current_user.is_authenticated %}

    <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
    
    
    <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
    {% else %}
    <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
    {%endif%}
  </ul>
  </div>
  </div>
  </div>

app/templates/new_review.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container">

        <div class="col-md-8">

            <img src="{{movie.poster}}" alt="{{movie.title}}" class="img-responsive">
        </div>

        <div class="col-md-4">

            {{ wtf.quick_form(review_form) }}
        </div>

    </div>

{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>
  <div class="col-md-4">
    {% if user.profile_pic_path %}

    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

    {%else%}
    <p>No profile picture</p>

    {% endif %}

  </div>
</div>
<br><br><br>
<h4>Change photo here</h4>

{% if user == current_user %}
<form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

  <input type="file"  name="photo" class="form-control" required>
  <input type="submit">
</form>
</div>
  {% endif %}


{% if user == current_user %}
   <center><a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a></center>
{% endif %}
{% endblock %}

app/templates/profile/update.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
<div class="container">
    {{wtf.quick_form(form)}}
</div>

{% endblock %}

app/templates/search.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}

{% block content %}
    <div class="container">

        <div class="row">

            <h3> Found {{ movies| count }} matches </h3>
            <hr>
            <ul>
                {{ macro.displayMovieList(movies)}}
            </ul>

        </div>

    </div>
{% endblock %}